### ISSUE TITLE
FFG Dice Stats calculator not loading completely

### ISSUE THREAD

**Issue by idontknow86** [gmathews42/FFG-dice-stats#1]
I recorded this video to demonstrate the non-functionality of the page/tool. 

I'm not sure if this is something on my end or not; I just updated Chrome OS this morning. I'm using the Chrome browser on Chrome OS Version 99.0.4844.57 (Official Build) (64-bit).

**Comment by gmathews42** [comment]
Required update of math.js from 7.1 to 10.4 (current version from host pagecdn)

**Comment by gmathews42** [comment]
math.js version update has fixed the problem
